### ISSUE TITLE
gist/transmission .config/settings.json being overwritten

### ISSUE THREAD

**Issue by vinifrancosilva** [vgist/dockerfiles#43]
Hey Guys,

I'm trying to setup the watch folder in a smb share.

Instead of using /data/.watch I want to use another directory.

That's my compose.yaml:
```

services:
  transmission:
    image: gists/transmission
    ports:
      - "8082:9091"
      - "51413:51413"
    volumes:
      - /srv/dev-disk-by-uuid-XYZ/torrents/docker_transmission_data:/data
    environment:
      - USERNAME=user
      - PASSWORD=1
    restart: always
```

Then I go to /srv/dev-disk-by-uuid-XYZ/torrents/docker_transmission_data/.config/settings.json and change the directory there.

I tried /data/watch (without the dot) just to see if it works and it does not.

Can you point out where I'm wrong?

Thank you.

**Comment by vinifrancosilva** [comment]
This solved the problem:

```
services:
  transmission:
    image: gists/transmission
    ports:
      - "8082:9091"
      - "51413:51413"
    volumes:
      - /srv/dev-disk-by-uuid-XYZ/torrents/docker_transmission_data:/data
      - /path/to/my/shared/watch/folder:/data/.watch
    environment:
      - USERNAME=user
      - PASSWORD=1
    restart: always
```
