### ISSUE TITLE
Logs time - not same as Server time region

### ISSUE THREAD

**Issue by wmar** [vgist/dockerfiles#5]
I had installed the Shadowsock via Docker into my Synology NAS, it logs always showing a different time of NAS machine which shall cause by different region setting.  No so sure that related to docker image or shadowsock lib container using default Region for all the logs.

**Comment by zgist** [comment]
@wmar 

command line try:

    -v /etc/localtime:/etc/localtime

compose file:

    volumes:
            - /etc/localtime:/etc/localtime:ro

**Comment by wmar** [comment]
Thanks for the fast reply!  Can u advice my office intuitive steps to do this with IMAGE execution!

**Comment by zgist** [comment]
@wmar 

1. Install docker & docker-compose with your package manager
2. Create folder and create docker-compose.yml file. e.g., `mkdir foo && cd "$_" && touch docker-compose.yml`
3. Write the following in docker-compose.yml
```
version: '3'

services:
    shadowsocks:
        container_name: shadowsocks
        image: gists/shadowsocks-libev
        ports:
            - "12345:8388/udp"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        networks:
            overlay:
        environment:
          - PASSWORD=your-passowrd
          - METHOD=chacha20-ietf-poly1305
        restart: always

      simple-obfs:
        container_name: obfs
        image: gists/simple-obfs
        ports:
            - "12345:8388/tcp"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - FORWARD=shadowsocks:8388
        depends_on:
            - shadowsocks
        networks:
            overlay:
        restart: always

networks:
    overlay:
        driver: bridge
```
4. `sudo docker-compose up -d`
5. open the firewall port 12345(or whatever you use).
